# Generated by Django 4.2.7 on 2023-11-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='null',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='white',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='party',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='voting.politicalparty'),
        ),
    ]
