# Generated by Django 4.2.7 on 2023-11-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_voting_vote_null_vote_white_alter_vote_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='party',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='vote',
            name='party_number',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
