# Generated by Django 4.2.7 on 2023-11-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_vote_party_remove_vote_voter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='completed',
            new_name='is_open',
        ),
    ]
