# Generated by Django 4.2.7 on 2023-11-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_rename_completed_voting_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='is_open',
            new_name='is_closed',
        ),
    ]
