# Generated by Django 4.2.7 on 2023-11-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_rename_is_open_voting_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Vote', 'verbose_name_plural': 'Votes'},
        ),
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'Voting'},
        ),
    ]
