# Generated by Django 4.2.7 on 2023-11-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_vote_options_alter_voting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='party_number',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
