# Generated by Django 4.2.7 on 2023-11-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_vote_party_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='party_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.politicalparty'),
        ),
    ]
